
export const timezones = [
  { value: "UTC", label: "🌍 UTC (Coordinated Universal Time)" },
  { value: "America/New_York", label: "🇺🇸 New York (Eastern Time)" },
  { value: "America/Chicago", label: "🇺🇸 Chicago (Central Time)" },
  { value: "America/Denver", label: "🇺🇸 Denver (Mountain Time)" },
  { value: "America/Los_Angeles", label: "🇺🇸 Los Angeles (Pacific Time)" },
  { value: "America/Toronto", label: "🇨🇦 Toronto" },
  { value: "America/Vancouver", label: "🇨🇦 Vancouver" },
  { value: "America/Sao_Paulo", label: "🇧🇷 São Paulo" },
  { value: "America/Argentina/Buenos_Aires", label: "🇦🇷 Buenos Aires" },
  { value: "Europe/London", label: "🇬🇧 London" },
  { value: "Europe/Paris", label: "🇫🇷 Paris" },
  { value: "Europe/Berlin", label: "🇩🇪 Berlin" },
  { value: "Europe/Rome", label: "🇮🇹 Rome" },
  { value: "Europe/Madrid", label: "🇪🇸 Madrid" },
  { value: "Europe/Amsterdam", label: "🇳🇱 Amsterdam" },
  { value: "Europe/Zurich", label: "🇨🇭 Zurich" },
  { value: "Europe/Stockholm", label: "🇸🇪 Stockholm" },
  { value: "Europe/Oslo", label: "🇳🇴 Oslo" },
  { value: "Europe/Helsinki", label: "🇫🇮 Helsinki" },
  { value: "Europe/Warsaw", label: "🇵🇱 Warsaw" },
  { value: "Europe/Prague", label: "🇨🇿 Prague" },
  { value: "Europe/Vienna", label: "🇦🇹 Vienna" },
  { value: "Europe/Budapest", label: "🇭🇺 Budapest" },
  { value: "Europe/Bucharest", label: "🇷🇴 Bucharest" },
  { value: "Europe/Athens", label: "🇬🇷 Athens" },
  { value: "Europe/Istanbul", label: "🇹🇷 Istanbul" },
  { value: "Europe/Moscow", label: "🇷🇺 Moscow" },
  { value: "Asia/Dubai", label: "🇦🇪 Dubai" },
  { value: "Asia/Riyadh", label: "🇸🇦 Riyadh" },
  { value: "Asia/Tehran", label: "🇮🇷 Tehran" },
  { value: "Asia/Karachi", label: "🇵🇰 Karachi" },
  { value: "Asia/Kolkata", label: "🇮🇳 Mumbai/Delhi (IST)" },
  { value: "Asia/Dhaka", label: "🇧🇩 Dhaka" },
  { value: "Asia/Bangkok", label: "🇹🇭 Bangkok" },
  { value: "Asia/Jakarta", label: "🇮🇩 Jakarta" },
  { value: "Asia/Singapore", label: "🇸🇬 Singapore" },
  { value: "Asia/Kuala_Lumpur", label: "🇲🇾 Kuala Lumpur" },
  { value: "Asia/Manila", label: "🇵🇭 Manila" },
  { value: "Asia/Hong_Kong", label: "🇭🇰 Hong Kong" },
  { value: "Asia/Shanghai", label: "🇨🇳 Beijing/Shanghai" },
  { value: "Asia/Taipei", label: "🇹🇼 Taipei" },
  { value: "Asia/Seoul", label: "🇰🇷 Seoul" },
  { value: "Asia/Tokyo", label: "🇯🇵 Tokyo" },
  { value: "Australia/Sydney", label: "🇦🇺 Sydney" },
  { value: "Australia/Melbourne", label: "🇦🇺 Melbourne" },
  { value: "Australia/Brisbane", label: "🇦🇺 Brisbane" },
  { value: "Australia/Perth", label: "🇦🇺 Perth" },
  { value: "Pacific/Auckland", label: "🇳🇿 Auckland" },
  { value: "Africa/Cairo", label: "🇪🇬 Cairo" },
  { value: "Africa/Lagos", label: "🇳🇬 Lagos" },
  { value: "Africa/Johannesburg", label: "🇿🇦 Johannesburg" },
  { value: "Africa/Nairobi", label: "🇰🇪 Nairobi" }
];
